[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
maxUploadSize = 20000

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0F6E4F"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F7F5"
textColor = "#16241E"
font = "sans serif"
