// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/geoportal-variants/DataTerrain.tsx": () => import("../components/mockups/geoportal-variants/DataTerrain.tsx"),
  "./components/mockups/geoportal-variants/ForestCanopy.tsx": () => import("../components/mockups/geoportal-variants/ForestCanopy.tsx"),
  "./components/mockups/geoportal-variants/SatelliteDark.tsx": () => import("../components/mockups/geoportal-variants/SatelliteDark.tsx")
};
